building/urls.py
from django.urls import path
from . import views

app_name = 'building'

urlpatterns = [
	path('edit/<int:id>', views.update_category),
	path('hapus/<int:id>', views.delete_category),
	path('list/<int:id>', views.list_category),
	path('categories/', views.categories),
	path('products/', views.products),
	path('add/', views.AddProduct),
	path('category/', views.addcategory),
	path('update/<int:id>', views.update),
	path('delete/<int:id>', views.delete),
	path('products/<int:id>', views.product),
	path('', views.product_list, name='product_list'),
	path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
	path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
]

cart/urls.py
from django.urls import path 
from . import views

app_name = 'cart'

urlpatterns = [
	path('', views.cart_detail, name='cart_detail'),
	path('add/<int:product_id>/', views.cart_add, name='cart_add'),
	path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

mybuilding/urls.py
from django.contrib import admin 
from django.urls import path, include 
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
	path('admin/', admin.site.urls),
	path('home/', views.index),
	path('user/', include('user.urls', namespace='user')),
	path('product_masuk/', include('product_masuk.urls', namespace='product_masuk')),
	path('supplier/', include('supplier.urls', namespace='supplier')),
	path('product_keluar/', include('product_keluar.urls', namespace='product_keluar')),
	path('accounts/', include('accounts.urls', namespace='accounts')),
	# path('customer/', include('customer.urls', namespace='customer')),
	path('orders/', include('orders.urls', namespace='orders')),
	path('cart/', include('cart.urls', namespace='cart')),
	path('', include('building.urls', namespace='building')),
	path('', include('django.contrib.auth.urls')),
]
if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path 
from . import views

app_name = 'orders'

urlpatterns = [
	path('delete/<int:id>/', views.delete_order),
	path('create/', views.order_create, name='order_create'),
	path('order/', views.orders),
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]
class CartAddProductForm(forms.Form):
	quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
	override = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)
	# timed = forms.DateTimeField(widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from building.models import Product
from .cart import Cart
from .forms import CartAddProductForm
from datetime import datetime, timedelta

@require_POST
def cart_add(request, product_id):
	cart = Cart(request)
	product = get_object_or_404(Product, id=product_id)
	# if request.method == 'POST':
	form = CartAddProductForm(request.POST)
	if form.is_valid():
		cd = form.cleaned_data
		now = datetime.now()
		cart.add(product=product, quantity=cd['quantity'], override_quantity=cd['override'])
		print(cart)
		return redirect('cart:cart_detail')
	# else:
	# 	form = CartAddProductForm()
	
	

@require_POST
def cart_remove(request, product_id):
	cart = Cart(request)
	product = get_object_or_404(Product, id=product_id)
	cart.remove(product)
	return redirect('cart:cart_detail')
	
def cart_detail(request):
	cart = Cart(request)
	now = datetime.now()
	jam = timedelta(hours=24)
	for item in cart:
		# h = item['timed']
		# print(h)
		# j = h + str(jam)
		# print(j)
		# if j < h: 
		# 	print(now)
		item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'], 'override': True})

	context = {
		"cart": cart, 
	} 
	return render(request, 'cart/detail.html', context)

templates/cart/detail.html
{% extends 'home.html' %}
{% load static %}

{% block title %}
	Keranjang Bahan Bangunan Anda
{% endblock %}

{% block content %}
<!-- Begin Page Content -->
<div class="container-fluid">

<!-- Page Heading -->
<h1 class="h-3 mb-2 text-gray-800">CART</h1>

<!-- DataTales Example -->
<div class="card shadow mb-4">
	<div class="card-header py-3">
		<h6 class="m-0 font-weight-bold text-primary">Keranjang Bahan Bangunan Anda</h6>
	</div>
	<div class="card-body">
		<div class="table-responsive">
			<table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
				<thead>
					<tr>
						<th>Image</th>
						<th>Product</th>
						<th>Quantity</th>
						<th>Remove</th>
						<th>Unit price</th>
						<th>Price</th>
					</tr>
				</thead>
				<tbody>
					{% for item in cart %}
					{% with product=item.product %}
					<tr>
						<td>
							<a href="{{ product.get_absolute_url }}">
								<img class="mr-3" height="50px:" width="80px:" src="{% if product.image %}{{ product.image.url}} {% else %}{% static 'img/no_image.png' %}{% endif %}">
							</a>
						</td>
						<td>{{ product.name }}</td>
						<td>
							<form action="/cart/add/{{product.id}}/" method="post">
								{{ item.update_quantity_form.quantity }}
								{{ item.update_quantity_form.override }}
								<input type="submit" class="btn btn-primary btn-sm" value="Update">
								{% csrf_token %}
							</form>
						</td>
						<td>
							<!-- <a href="/cart/remove/{{product.id}}/" class="btn btn-danger btn-sm" method="post">Remove</a> -->
							<form action="/cart/remove/{{product.id}}/" method="post">
								<input type="submit" class="btn btn-danger btn-sm" value="Remove">
								{% csrf_token %}
							</form>
						</td>
						<td class="num">Rp. {{ item.price }}</td>
						<td class="num">Rp. {{ item.total_price }}</td>
					</tr>
					{% endwith %}
					{% endfor %}
					<tr class="total">
						<td>Total</td>
						<td colspan="4"></td>
						<td class="num">Rp. {{ cart.get_total_price }}</td>
					</tr>
				</tbody>
			</table>
			<div class="d-grid gap-2 d-md-flex justify-content-md-end">
				<a href="{% url 'building:product_list' %}" class="btn btn-secondary btn-sm mr-3" role="button" data-bs-toggle="button">Lanjut Belanja</a>
				<a href="{% url 'orders:order_create' %}" class="btn btn-primary btn-sm" role="button" data-bs-toggle="button">Checkout</a>
			</div>
		</div>
    </div>
</div>

</div>
<!-- /.container-fluid -->

</div>
<!-- End of Main Content -->	
{% endblock %}