building/urls.py
from django.urls import path
from . import views

app_name = 'building'

urlpatterns = [
	path('edit/<int:id>', views.update_category),
	path('hapus/<int:id>', views.delete_category),
	path('list/<int:id>', views.list_category),
	path('categories/', views.categories),
	path('products/', views.products),
	path('add/', views.AddProduct),
	path('category/', views.addcategory),
	path('update/<int:id>', views.update),
	path('delete/<int:id>', views.delete),
	path('products/<int:id>', views.product),
	path('', views.product_list, name='product_list'),
	path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
	path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
]

cart/urls.py
from django.urls import path 
from . import views

app_name = 'cart'

urlpatterns = [
	path('', views.cart_detail, name='cart_detail'),
	path('add/<int:product_id>/', views.cart_add, name='cart_add'),
	path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

mybuilding/urls.py
from django.contrib import admin 
from django.urls import path, include 
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
	path('admin/', admin.site.urls),
	path('home/', views.index),
	path('user/', include('user.urls', namespace='user')),
	path('product_masuk/', include('product_masuk.urls', namespace='product_masuk')),
	path('supplier/', include('supplier.urls', namespace='supplier')),
	path('product_keluar/', include('product_keluar.urls', namespace='product_keluar')),
	path('accounts/', include('accounts.urls', namespace='accounts')),
	# path('customer/', include('customer.urls', namespace='customer')),
	path('orders/', include('orders.urls', namespace='orders')),
	path('cart/', include('cart.urls', namespace='cart')),
	path('', include('building.urls', namespace='building')),
	path('', include('django.contrib.auth.urls')),
]
if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

building/models.py
from django.db import models
from django.urls import reverse

class Category(models.Model):
	name = models.CharField(max_length=200, db_index=True)
	slug = models.SlugField(max_length=200, unique=True)

	def get_absolute_url(self):
		return reverse('building:product_list_by_category', args=[self.slug])

	class Meta:
		ordering = ('name',)
		verbose_name = 'category'
		verbose_name_plural = 'categories'

		def __str__(self):
			return self.name


class Product(models.Model):
	category 	= models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
	name 	 	= models.CharField(max_length=200, db_index=True)
	slug 	 	= models.SlugField(max_length=200, db_index=True)
	image    	= models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
	description = models.TextField(blank=True)
	price 		= models.DecimalField(max_digits=10, decimal_places=2)
	stock		= models.IntegerField()
	satuan 		= models.CharField(max_length=25)
	available 	= models.BooleanField(default=True)
	created 	= models.DateTimeField(auto_now_add=True)
	updated 	= models.DateTimeField(auto_now=True)


	def get_absolute_url(self):
		return reverse('building:product_detail', args=[self.id, self.slug])

	class Meta:
		ordering = ('name',)
		index_together = (('id', 'slug'),)

	def __str__(self):
		return self.name

building/forms.py
from django import forms
from .models import Product, Category


class ProductForm(forms.ModelForm):
	category 		= forms.ModelChoiceField(queryset=Category.objects.all())
	name 	 		= forms.CharField()
	slug 			= forms.CharField()
	image 			= forms.ImageField()
	description 	= forms.CharField(widget=forms.Textarea)
	price 			= forms.DecimalField()
	stock 			= forms.IntegerField()
	satuan			= forms.CharField()
	#available = forms.BooleanField(widget=forms.RadioSelect(choices=YES_NO))

	class Meta: 
		fields = ('category', 'name', 'slug', 'image','description', 'price', 'stock', 'satuan')
		model = Product

class CategoryForm(forms.ModelForm):
	name = forms.CharField()
	slug = forms.CharField()

	class Meta:
		fields = ('name', 'slug')
		model = Category

building/views.py
from django.db.models import query
from django.shortcuts import render, get_object_or_404, redirect
from .models import Category, Product 
from cart.forms import CartAddProductForm
from .forms import ProductForm, CategoryForm

# def home(request):
# 	return render(request, 'home.html')

def AddProduct(request):
    #if not request.user.is_staff or not request.user.is_superuser:
    	#raise Http404

    form = ProductForm(request.POST or None, request.FILES or None)
    if form.is_valid():
    	instance = form.save(commit=False)
    	instance.available = True
    	instance.save()
    	# message success 
    	#message.success(request, "Successfully")
    	return redirect("/products")
    context = {
    	"form": form,
    }
    return render(request, 'building/product/form.html', context)

def product_list(request, category_slug=None):
	category =None
	categories = Category.objects.all()
	products = Product.objects.filter(available=True)
	if category_slug:
		category = get_object_or_404(Category, slug=category_slug)
		products = products.filter(category=category)
	return render(request, 'building/product/list.html', {'category': category, 'categories': categories, 'products': products})

def product_detail(request, id, slug):
	product = get_object_or_404(Product, id=id, slug=slug, available=True)
	cart_product_form = CartAddProductForm()
	return render(request, 'building/product/detail.html', {'product': product, 'cart_product_form': cart_product_form})

def products(request):
	products = Product.objects.all()
	context = {
		"products":products
	}
	return render(request, 'building/product/products.html', context) 

def addcategory(request):
	form = CategoryForm(request.POST or None)
	if form.is_valid():
		instance = form.save(commit=False)
		instance.save()
		# message success 
		# message.success(requidest, "Successfully")
		return redirect("/categories")
	context = {
		"form": form,
	}
	return render(request, 'building/category.html', context)

def product(request, id):
	product = get_object_or_404(Product, id=id)
	context = {
		"product": product,
	}
	return render(request, 'building/product/product.html', context)

def update(request, id):
	instance = get_object_or_404(Product, id=id)
	form = ProductForm(request.POST or None, request.FILES or None, instance=instance)
	if form.is_valid():
		instance = form.save(commit=False)
		instance.save()
		return redirect("/products" )
	context = {
		"instance": instance,
		"form": form,
	}
	return render(request, 'building/product/form.html', context)

def delete(request, id):
	instance = get_object_or_404(Product, id=id)
	instance.delete()
	#messages.success(request, "Successfully Deleted")
	return redirect("/products")

def update_category(request, id):
	instance = get_object_or_404(Category, id=id)
	form = CategoryForm(request.POST or None, instance=instance)
	if form.is_valid():
		instance = form.save(commit=False)
		instance.save()
		return redirect("/categories" )
	context = {
		"instance": instance,
		"form": form,
	}
	return render(request, 'building/category.html', context)

def delete_category(request, id):
	instance = get_object_or_404(Category, id=id)
	instance.delete()
	#messages.success(request, "Successfully Deleted")
	return redirect("/categories")

def categories(request):
	categories = Category.objects.all()
	context = {
		"categories": categories,
	}
	return render(request, 'building/categories.html', context)

def list_category(request, id):
	category = get_object_or_404(Category, id=id)
	context = {
		"category": category,
	}
	return render(request, 'building/list_category.html', context)
	

templates/building/base.html
{% extends 'home.html' %}
{% load static %}

{% block content %}
	<div class="container-fluid">
		<div class="card shadow mb-4">
			<div class="card-header py-3" id="header">
				<a href="/" class="logo">My Building</a>
			</div>
			<div id="subheader">
				<div class="cart">
				</div>
			</div>
			<div id="content">
				{% block content %}
				{% endblock %}
			</div>
			<div class="cart">
				{% with total_items=cart|length %}
					{% if total_items > 0 %}
						Your cart:
						<a href="{% url 'cart:cart_detail' %}">
							{{ total_items }} item{{ total_items|pluralize }}, ${{ cart.get_total_price }}
						</a>
					{% else %}
						Your cart is empty.
					{% endif %}
				{% endwith %}
			</div>
		</div>
	</div>
{% endblock %}

templates/building/categories.html
{% extends 'home.html' %}
{% load static %}

{% block content %}
<!-- Begin Page Content -->
<div class="container-fluid">

<!-- Page Heading -->
<h1 class="h-3 mb-2 font-weight-bold text-gray-800">Data Categories</h1>

<!-- DataTales Example -->
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <div class="d-grid gap-2 d-md-flex justify-content-md-end">
            <a href="/category" class="btn btn-primary btn-sm" role="button" data-bs-toggle="button">Tambah Category</a>
        </div>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Slug</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for category in categories %}
                    <tr>
                        <td>{{category.name}}</td>
                        <td>{{category.slug}}</td>
                        <td>
                            <a href="/edit/{{category.id}}"><i class="fa fa-edit"></i></a>
                            <a href="/hapus/{{category.id}}"><i class="fa fa-trash"></i></a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

</div>
<!-- /.container-fluid -->

</div>
<!-- End of Main Content -->
{% endblock content %}

templates/building/category.html
{% extends 'home.html' %}
{% load widget_tweaks %}
{% load static %}

{% block content %}
<div class="container-fluid">
	<h1 class="h3 mb-2 font-weight-bold text-primary">Tambah Category</h1>
	<div class="card shadow mb-4">
		<div class="card-header py-3">

			<form method="post">
				{% csrf_token %}

				{{ form.non_field_errors }}

				{% for hidden in form.hidden_fields %}
					{{ hidden_field.errors }}
					{{ hidden_field }}
				{% endfor %}

				{% for field in form.visible_fields %}
				<div class="form-group mb-4">
					<label for="{{ field.id_for_label }}">{{ field.label }}</label>
					{% render_field field class="form-control" %}
					{% for error in field.errors %}
						<span class="help-block">{{ error }}</span>
					{% endfor %}
				</div>
				{% endfor %}
				
				<div class="form-group">
					<button type="submit" class="btn btn-outline-primary">Submit</button>
					<a href="/categories" class="btn btn-outline-secondary">Cancel</a>
				</div>
				
			</form>
		</div>
	</div>
</div>




	<!-- <div class="i-am-centered">
		<form method="POST" novalidate>
			{% csrf_token %}
			<div class="form-group">
				<label>Name</label>
				{{ form.name }}
			</div>
			<div class="form-group">
				<label>Slug</label>
				{{ form.slug }}
			</div>
				<button type="submit" class="btn btn-primary">Submit</button>
		</form>
	</div> -->
{% endblock content %}

templates/building/list_category.html
{% extends 'home.html' %}
{% load static %}

{% block content %}
<div id="sidebar">
	<h3>Categories</h3>
	<ul>
		<li {% if not category %}class="selected"{% endif %}>
			<a href="{% url 'building:product_list' %}"></a>
		</li>
		{% for c in categories %}
			<li {% if category.slug == c.slug %}class="selected"{% endif %}>
				<a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
			</li>
		{% endfor %}
	</ul>
</div>
{% endblock %}